title:              Omar YAYA
greeting:           Hi, I'm Omar
description:        Senior Software Engineer (Full-stack) | Certified ScrumMaster® (CSM®)
author: Omar YAYA
baseurl:           "/"
url:               "https://omaryaya.com"

# Social Profiles
default_username: omaryaya
twitter_username:   OmarYayaa
github_username:    omaryaya
instagram_username:  yayaa.omar
linkedin_username:  omaryaya
devto_username:  omaryaya

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-217466661-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Conversion
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# SEO
twitter:
  username: OmarYayaa
  card: summary

logo: img/omar/Omar-Avatar.png

social:
  name: Omar YAYA
  links:
    - https://twitter.com/OmarYayaa
    - https://www.linkedin.com/in/omaryaya
    - https://github.com/omaryaya
    - https://www.instagram.com/yayaa.omar
