title:              Omar YAYA
email:              omar.yaya.work@gmail.com
description:        Welcome to Omar YAYA Personal Website
author:             Omar YAYA
baseurl:            "/"
url:                "https://omaryaya.github.io"
# https://omaryaya.github.io/omar-blog-2

# Social Profiles
twitter_username:   OmarYayaa
github_username:    omaryaya
instagram_username:  yayaa.omar
linkedin_username:  omaryaya

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
